export const Nav = ()=>{
    return(
        <nav>
            <ul>
                <li>
                    Inicio
                </li>
                <li>
                    Empresa
                </li>
                <li>
                    Proyecto
                </li>
                <li>
                    Contacto
                </li>
            </ul>
        </nav>
    )
}